apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: flight-scheduler
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 20s"
    - name: route
      value: "/scheduler"
scopes:
- flight
